// <auto-generated />
using System;
using AppointmentManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppointmentManagement.Persistence.Migrations
{
    [DbContext(typeof(AppointmentManagementDbContext))]
    [Migration("20230129114009_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppointmentManagement.Domain.Entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Shiva",
                            LastName = "Kiaee",
                            PhoneNumber = "07123456789"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Eva",
                            LastName = "King",
                            PhoneNumber = "07123456710"
                        });
                });

            modelBuilder.Entity("AppointmentManagement.Domain.Entities.AgentAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("AgentAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 1
                        },
                        new
                        {
                            Id = 3,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 1
                        },
                        new
                        {
                            Id = 4,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 1
                        },
                        new
                        {
                            Id = 5,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 1
                        },
                        new
                        {
                            Id = 6,
                            AgentId = 1,
                            Date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 1
                        },
                        new
                        {
                            Id = 7,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 2
                        },
                        new
                        {
                            Id = 8,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 2
                        },
                        new
                        {
                            Id = 9,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 2
                        },
                        new
                        {
                            Id = 10,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 2
                        },
                        new
                        {
                            Id = 11,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 2
                        },
                        new
                        {
                            Id = 12,
                            AgentId = 1,
                            Date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 2
                        },
                        new
                        {
                            Id = 13,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 3
                        },
                        new
                        {
                            Id = 14,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 3
                        },
                        new
                        {
                            Id = 15,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 3
                        },
                        new
                        {
                            Id = 16,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 3
                        },
                        new
                        {
                            Id = 17,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 3
                        },
                        new
                        {
                            Id = 18,
                            AgentId = 1,
                            Date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 3
                        },
                        new
                        {
                            Id = 19,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 4
                        },
                        new
                        {
                            Id = 20,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 4
                        },
                        new
                        {
                            Id = 21,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 4
                        },
                        new
                        {
                            Id = 22,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 4
                        },
                        new
                        {
                            Id = 23,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 4
                        },
                        new
                        {
                            Id = 24,
                            AgentId = 1,
                            Date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 4
                        },
                        new
                        {
                            Id = 25,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 5
                        },
                        new
                        {
                            Id = 26,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 5
                        },
                        new
                        {
                            Id = 27,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 5
                        },
                        new
                        {
                            Id = 28,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 5
                        },
                        new
                        {
                            Id = 29,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 5
                        },
                        new
                        {
                            Id = 30,
                            AgentId = 1,
                            Date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 5
                        },
                        new
                        {
                            Id = 31,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 6
                        },
                        new
                        {
                            Id = 32,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 6
                        },
                        new
                        {
                            Id = 33,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 6
                        },
                        new
                        {
                            Id = 34,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 6
                        },
                        new
                        {
                            Id = 35,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 6
                        },
                        new
                        {
                            Id = 36,
                            AgentId = 1,
                            Date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 6
                        },
                        new
                        {
                            Id = 37,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 7
                        },
                        new
                        {
                            Id = 38,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 7
                        },
                        new
                        {
                            Id = 39,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 7
                        },
                        new
                        {
                            Id = 40,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 7
                        },
                        new
                        {
                            Id = 41,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 7
                        },
                        new
                        {
                            Id = 42,
                            AgentId = 1,
                            Date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 7
                        },
                        new
                        {
                            Id = 43,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 8
                        },
                        new
                        {
                            Id = 44,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 8
                        },
                        new
                        {
                            Id = 45,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 8
                        },
                        new
                        {
                            Id = 46,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 8
                        },
                        new
                        {
                            Id = 47,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 8
                        },
                        new
                        {
                            Id = 48,
                            AgentId = 1,
                            Date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 8
                        },
                        new
                        {
                            Id = 49,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 9
                        },
                        new
                        {
                            Id = 50,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 9
                        },
                        new
                        {
                            Id = 51,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 9
                        },
                        new
                        {
                            Id = 52,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 9
                        },
                        new
                        {
                            Id = 53,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 9
                        },
                        new
                        {
                            Id = 54,
                            AgentId = 1,
                            Date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 9
                        },
                        new
                        {
                            Id = 55,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 10
                        },
                        new
                        {
                            Id = 56,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 10
                        },
                        new
                        {
                            Id = 57,
                            AgentId = 1,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 10
                        },
                        new
                        {
                            Id = 58,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 10
                        },
                        new
                        {
                            Id = 59,
                            AgentId = 2,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 10
                        },
                        new
                        {
                            Id = 60,
                            AgentId = 1,
                            Date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeSlotId = 10
                        });
                });

            modelBuilder.Entity("AppointmentManagement.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AgentAvailabilityId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerMessage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgentAvailabilityId")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("AppointmentManagement.Domain.Entities.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<TimeSpan>("From")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("To")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            From = new TimeSpan(0, 9, 0, 0, 0),
                            To = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            From = new TimeSpan(0, 9, 30, 0, 0),
                            To = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            From = new TimeSpan(0, 10, 0, 0, 0),
                            To = new TimeSpan(0, 10, 30, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            From = new TimeSpan(0, 10, 30, 0, 0),
                            To = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            From = new TimeSpan(0, 11, 0, 0, 0),
                            To = new TimeSpan(0, 11, 30, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            From = new TimeSpan(0, 11, 30, 0, 0),
                            To = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            From = new TimeSpan(0, 12, 0, 0, 0),
                            To = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            From = new TimeSpan(0, 12, 30, 0, 0),
                            To = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            From = new TimeSpan(0, 13, 0, 0, 0),
                            To = new TimeSpan(0, 13, 30, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            From = new TimeSpan(0, 13, 30, 0, 0),
                            To = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            From = new TimeSpan(0, 14, 0, 0, 0),
                            To = new TimeSpan(0, 14, 30, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            From = new TimeSpan(0, 14, 30, 0, 0),
                            To = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            From = new TimeSpan(0, 15, 0, 0, 0),
                            To = new TimeSpan(0, 15, 30, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            From = new TimeSpan(0, 15, 30, 0, 0),
                            To = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            From = new TimeSpan(0, 16, 0, 0, 0),
                            To = new TimeSpan(0, 16, 30, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            From = new TimeSpan(0, 16, 30, 0, 0),
                            To = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            From = new TimeSpan(0, 17, 0, 0, 0),
                            To = new TimeSpan(0, 17, 30, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            From = new TimeSpan(0, 17, 30, 0, 0),
                            To = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            From = new TimeSpan(0, 18, 0, 0, 0),
                            To = new TimeSpan(0, 18, 30, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            From = new TimeSpan(0, 18, 30, 0, 0),
                            To = new TimeSpan(0, 19, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("AppointmentManagement.Domain.Entities.AgentAvailability", b =>
                {
                    b.HasOne("AppointmentManagement.Domain.Entities.Agent", "Agent")
                        .WithMany("AgentAvailabilities")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppointmentManagement.Domain.Entities.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("AppointmentManagement.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("AppointmentManagement.Domain.Entities.AgentAvailability", "AgentAvailability")
                        .WithOne("Appointment")
                        .HasForeignKey("AppointmentManagement.Domain.Entities.Appointment", "AgentAvailabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentAvailability");
                });

            modelBuilder.Entity("AppointmentManagement.Domain.Entities.Agent", b =>
                {
                    b.Navigation("AgentAvailabilities");
                });

            modelBuilder.Entity("AppointmentManagement.Domain.Entities.AgentAvailability", b =>
                {
                    b.Navigation("Appointment");
                });
#pragma warning restore 612, 618
        }
    }
}
